# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5515a39302245a8fdbb56da8e20f6c873ef22f3f79c847e97d88a74a6502beb0bb7e13fd4d4ceaa071e49637ce97aeb571ba3d60c5691f08f8b5124bce5182b9

test:
  secret_key_base: cedd6585873789567ff31ce4805bcff691a77a2f6d02eddadb1b56dab22f731bb3dec750c422ee044b20d9398b911d9af794e64ace8536bd5c00c391f7e6131c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
